### PR TITLE
Do not load corrupted duplicate block indexes.

### LINKED ISSUE #422: Startup Crash: chain.cpp:105: const CBlockIndex* CBlockIndex::GetAncestor(int) const: Assertion `pindexWalk->pprev' failed.
After a graceful shutdown, during a blockchain sync, the following startup error appears:

```
veil-qt: chain.cpp:105: const CBlockIndex* CBlockIndex::GetAncestor(int) const: Assertion `pindexWalk->pprev' failed.
Aborted (core dumped)
```

Expected: Wallet could start normally or handle issues

Actual: Error above, hard crash

Reliability: Every time once it happens

Version: Veil 1.0.2, Ubuntu 18.04 x64

### PR DESCRIPTION
**Pull request by presstab**
fixes #422
It is also possible that #405 is related, but not positive.

For some reason multiple indexes are being saved to disk for the same block. The second index will overwrite the first index on first load. The second index has `nTx` set to `0`, as well as all relevant block file locations. The second index causes all subsequent indexes to have `nChainTx` set to `0`, causing them not to be able to be considered block candidates. Also notable is that the second index has the wrong database key which is supposed to be the block hash but is not.

This change simply ignores the second block index on first load. It is still yet to be determined what causes the duplicate index.

### CODE REVIEW

File: src/txdb.cpp [hunk 1]
```diff
@@ -258,6 +258,8 @@ bool CBlockTreeDB::LoadBlockIndexGuts(const Consensus::Params& consensusParams,
     std::unique_ptr<CDBIterator> pcursor(NewIterator());
 
     pcursor->Seek(std::make_pair(DB_BLOCK_INDEX, uint256()));
+    
+    std::set<uint256> setBlockHash;
```
Comment (blondfrogs) [inline src/txdb.cpp]: This set doesn't seem to be used. Should be removed if it isn't being used

Comment (presstab) [reply src/txdb.cpp]: Good spot. Left over garbage. Fixed.
