### PR TITLE
Provide Signature/Verification facility with Stealth addresses.

### LINKED ISSUE #311: Sign message function is not working.
The sign message function was unable to sign a message with an address chosen in its interface.

I expected, when I chose an address from the list provided, that I could sign the message I typed.

It displayed an error message. ```The entered address does not refer to a key. Please check the address and try again.```

I tried this on basecoin and stealth addresses and it happened each time. I also tried it on my testnet wallet, which contained funds. I only had a stealth address in this, and got the same message.

To get to the Sign Message or Verify Message window, (in MacOS) click and hold the mouse on the Veil wallet's Dock icon, then it gives you a number of choices, including "Sign message" and "Verify message". 

1.0.0.10

Mac Pro (3.5GHz 6-core Xeon, SSD, 32 GB RAM)

Also in the address chooser it refers to **Bitcoin** address, so I'm wondering if this feature was not looked at by the Veil team. This is a different address chooser than you get in the main Veil wallet window. 

I didn't find anything in the debug log that referred to the error message.

### PR DESCRIPTION
**Pull request by drag0ng**
Fixes #311

### CODE REVIEW

File: src/qt/signverifymessagedialog.cpp [hunk 1]
```diff
@@ -120,8 +120,17 @@ void SignVerifyMessageDialog::on_signMessageButton_SM_clicked()
         ui->statusLabel_SM->setText(tr("The entered address is invalid.") + QString(" ") + tr("Please check the address and try again."));
         return;
     }
-    const CKeyID* keyID = boost::get<CKeyID>(&destination);
-    if (!keyID) {
+
+    CKeyID* keyID = NULL;;
```
Comment (presstab) [inline src/qt/signverifymessagedialog.cpp]: double semicolon typo. Also since Veil uses c++11, this should be `nullptr`.

File: src/qt/signverifymessagedialog.cpp [hunk 2]
```diff
@@ -120,8 +120,17 @@ void SignVerifyMessageDialog::on_signMessageButton_SM_clicked()
...
+    CStealthAddress* stealthID = NULL;
```
Comment (presstab) [inline src/qt/signverifymessagedialog.cpp]: replace with `nullptr`

File: src/qt/signverifymessagedialog.cpp [hunk 3]
```diff
@@ -198,10 +208,20 @@ void SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked()
         ui->statusLabel_VM->setText(tr("The entered address is invalid.") + QString(" ") + tr("Please check the address and try again."));
         return;
     }
-    if (!boost::get<CKeyID>(&destination)) {
-        ui->addressIn_VM->setValid(false);
-        ui->statusLabel_VM->setStyleSheet("QLabel { color: red; }");
-        ui->statusLabel_VM->setText(tr("The entered address does not refer to a key.") + QString(" ") + tr("Please check the address and try again."));
+
+    CKeyID* keyID = NULL;;
```
Comment (presstab) [inline src/qt/signverifymessagedialog.cpp]: double semicolon + replace with `nullptr`

File: src/qt/signverifymessagedialog.cpp [hunk 4]
```diff
@@ -198,10 +208,20 @@ void SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked()
...
+    CStealthAddress* stealthID = NULL;
```
Comment (presstab) [inline src/qt/signverifymessagedialog.cpp]: replace with `nullptr`

**Comment by drag0ng** [comment]
> Signing of message with basecoin address did not work for me:
> 
> ```
> << getnewbasecoinaddress
> >> bv1qqxa0gtnpgarq2fs9zz6p7ve5fe08tgrcj9usyy
> 
> << signmessage "bv1qqxa0gtnpgarq2fs9zz6p7ve5fe08tgrcj9usyy" "testing#478"
> >> Address does not refer to key (code -3)
> ```
> 
> Signing with stealth address does not work for me:
> 
> ```
> << getnewaddress
> >> sv1qqpt56pkx84zavn3pjgzht5quakukej896y9whefq66lqh8mt08je8qpqvpnh3pfsujaxe46908539tmwfehnrr52cjg2f2fe4d72v5yek0m2qqqzvvqzu
> 
> << signmessage "sv1qqpt56pkx84zavn3pjgzht5quakukej896y9whefq66lqh8mt08je8qpqvpnh3pfsujaxe46908539tmwfehnrr52cjg2f2fe4d72v5yek0m2qqqzvvqzu" "testing#478"
> >> Address does not refer to key (code -3)
> ```

I believe this issue was referring to the signature functionality failing in the UI.
Did not know that there is no functionality of signature at all in the core. Will try to fix on the wallet side too.

File: src/qt/signverifymessagedialog.cpp (hunk 3 above)
Comment (drag0ng) [reply src/qt/signverifymessagedialog.cpp]: Fixed

File: src/qt/signverifymessagedialog.cpp (hunk 4 above)
Comment (drag0ng) [reply src/qt/signverifymessagedialog.cpp]: Fixed.

**Comment by drag0ng** [comment]
@presstab  The updated change should work for signing and verification of pubID, stealthID and WitnessID.

**Comment by presstab** [comment]
Signing appears to work now, but issues with verification of the signed message:
```
<< signmessage "bv1qe7ngz6syudlnxr2tpca8lyfejxsa48588wz9ya" "testing#478"
>> IDeuQ07z9jk/TIFtU4S0Iu69U8ONA0M0JUGL6H4GBmNJIbr/gqgpIEu1EUJQ9dhXAiJfbc7y9WYg8rpBewtzypA=

<< verifymessage "bv1qe7ngz6syudlnxr2tpca8lyfejxsa48588wz9ya" "IDeuQ07z9jk/TIFtU4S0Iu69U8ONA0M0JUGL6H4GBmNJIbr/gqgpIEu1EUJQ9dhXAiJfbc7y9WYg8rpBewtzypA=" "testing#478"
>> Address does not refer to key (code -3)

<< signmessage "sv1qqp0mnd8dxevd5v9rg7mky7rxvgcgxznla3vwl9mz32sdznvexx48sgpqdfm0d29ac6fadwmcf442cth4l85pr82ca374ugxn8dxtcrgnhpl6qqq7x0aqc" "testing#478"
>> IFmZKtIUIRPYbN6WDHbLaXQxVqaFGaYObVDFj+6W8vtYRtYNHaqeAJu7BaEdLgpSyf62CpBBEaB/7QHGD34OHd4=

<< verifymessage "sv1qqp0mnd8dxevd5v9rg7mky7rxvgcgxznla3vwl9mz32sdznvexx48sgpqdfm0d29ac6fadwmcf442cth4l85pr82ca374ugxn8dxtcrgnhpl6qqq7x0aqc" "IFmZKtIUIRPYbN6WDHbLaXQxVqaFGaYObVDFj+6W8vtYRtYNHaqeAJu7BaEdLgpSyf62CpBBEaB/7QHGD34OHd4=" "testing#478"
>> Address does not refer to key (code -3)

```

**Comment by drag0ng** [comment]
Updated the VerifyMessage rpc too.

**Comment by presstab** [comment]
```
<< signmessage "bv1qwn3rsx0k0mcxq3vexqe9aqnzpzrg088lpn4zw8" "testing#478"
>> ILPZd2ygrDmQESPuogv+kG5mYC9qz5jDbEMlZtBlITkYDavAYc+sVW9NIh26jYNQfb1+UpsyDBbYW3qeYzumguY=

<< verifymessage "bv1qwn3rsx0k0mcxq3vexqe9aqnzpzrg088lpn4zw8" "ILPZd2ygrDmQESPuogv+kG5mYC9qz5jDbEMlZtBlITkYDavAYc+sVW9NIh26jYNQfb1+UpsyDBbYW3qeYzumguY=" "testing#478"
>> true


```

**Comment by drag0ng** [comment]
sv1qqp78ccvc5xexhvj6u9zkvqhwv86lavgxgct9uykaa63jle4k79xprqpqv8888p9pl88euv6edgjw926xhm6znc63fw7lfgyz4z70k44w5d3gqqq5ddeah
