### PR TITLE
Fix wrong CT / RingCT amounts in transaction history when wallet locked

### LINKED ISSUE #922: Make automated rescanringctwallet and friendly message enabling exchanges to send to stealth without worrying recipients
Exchanges are only sending to basecoin. Users are worried when receiving stealth txs.

 
  Noobs need the process of confidently receiving stealth funds to be noob-friendly, even grandma, executive, or trainee / intern friendly.

  The Vinex exchange very early in Veil history tried sending withdrawals to SV addresses, but customers thought they only received a single Satoshi of Veil as their wallet was locked at the time. This lead Vinex to suspend withdrawals to stealth addresses due to support workload. 

 If the wallet is locked when processing the block containing the transaction, it will (in the recipient's wallet) have a placeholder value of one satoshi only. After unlocking it is necessary to `rescanringctwallet`. This needs to be automated if a received transaction has been detected, and a friendly message needs to be generated for the GUI QtWallet user and for RPC-using  exchanges alike. 

My write-up in Discord:

> The only exchange that did implement stealth withdrawals was Vinex, early on, but when people began receiving stealth transactions while their wallets were locked and therefore it just looked like they received a (placeholder amount of) 1 satoshi of Veil, support requests increased. It turns out that if your wallet is locked when you receive a stealth payment you have to unlock your wallet and do rescanringctwallet in the Debug Console (or the equivalent command in Terminal).
> 
> In the future, so that exchanges can send and receive stealth transactions I would like to see the wallet give a message like "You have received a payment. Please unlock your wallet so the amount can be decrypted." Then it should automatically rescanringctwallet, which only takes a few seconds in most cases. [There would be no need to add "stealth" to describe "a payment", because Veil transactions are normally stealth and eliminating basecoin transactions as a norm, such as from mining pools or to and from exchanges, will achieve this overwhelmingly.]

Much of this, I believe is already planned for the RingCT release, but I am posting this on the suggestion of a user, in relation at least to the friendly notification mentioned in the second paragraph. I don't see any specific related issues although I believe plans and intentions have been previously discussed. Please add any references if found.

### PR DESCRIPTION
**Pull request by us77ipis**
### Problem
When receiving a CT transaction while the wallet is locked (or unlocked for staking only), the amount displayed in the transaction history is wrong, and keeps wrong until a `rescanringctwallet` rpc is called and the wallet is restarted.

### Root Cause
- More concretely the wrong amount showed is -1 satoshi per output in the transaction, which comes from the default value in the following line: https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/veil/ringct/outputrecord.h#L43
- Furthermore, for the case when the transaction contained a change output, there was a bug in the way the GUI calculates the transaction amount, which resulted in that default -1 satoshi also being added for the change output (which isn't owned by the receiving wallet), thus the final amount was in this case always displayed as 1 satoshi less than the actual transaction was.
- For incoming RingCT transactions the `ORF_OWNED` flag was not set correctly, leading to RingCT transactions being showed as "(n/a)" in the transaction history, if they arrived while the wallet was locked.

### Solution
- When a CT transaction arrives while the wallet is locked (or unlocked for staking only):
  - Instead of a wrong amount show **"Hidden"** in the transaction history entry.
  - In the tooltip of the transaction row show the message **"Unlock wallet to see hidden amount"**.
  - In the "Incoming transaction" GUI notification also show "Hidden" instead of a wrong amount.
- Fix `rescanringctwallet` to properly update corresponding entries in the transaction history GUI.
- Keep track of locked transactions and when the wallet is then unlocked, automatically do a **partial `rescanringctwallet`** which only rescans those tracked locked transactions, and thus should be fast also for wallets having a very long transaction history.

### Bounty Payment Address
`sv1qqpjsrc60t60jhaywj5krmwla52ska70twc7wun6qnee65guxhvtxegpqwhuxypra4jn3pq86s24ryltcw6g2ss4573hyqac9u4g23m9mvxpyqqqwny49k`

### Testing Results
- Tested by sending basecoin/CT/RingCT from one testnet wallet to CT/RingCT of another testnet wallet, where the received amount showed up first as "Hidden" and once the wallet was unlocked, it showed the correct amount.
- Tested unlocking of the wallet while the transactions are still unconfirmed.
- Tested restarting the wallet between transaction arrival and unlocking of the wallet (state consistency across wallet restarts).

Fixes #922, #668

### CODE REVIEW

**Comment by us77ipis** [comment]
The current changes of the PR already work and solve the problem. However, it is still marked as draft because currently when the wallet is unlocked it does the full `rescanringctwallet` in the UI thread, which I don't think is a good idea. We could do one of the following things (or both?) to optimize this:
- Do `rescanringctwallet` in another thread, when the wallet is unlocked.
- Don't do a full `rescanringctwallet`, but instead keep track of "locked" transactions and then only specifically rescan those when the wallet is unlocked.

**Comment by us77ipis** [comment]
Btw. what will the bounty be for solving this soon three year old issue with as far as I can read in #922 quite high impact for Veil users :wink: ?

**Comment by seanPhill** [comment]
I've got this PR running on Testnet, and firstly ran the released standard released version, to compare, but this time, unlocking has so far taken 2.5 hours, and is continuing to show the macOS beach ball of waiting, and no progress in the debug log. :( Admittedly, this wallet is normally slow (because the wallet.dat file is moderately large, and it has done a huge number of stakes and spends), but not like this. I have been able to rescanringctwallet with no problem, but with PR1001 it's just not completing. This is programmed to only do a single rescanringctwallet upon unlock, right?
There was probably at least thirty or forty ringct incoming transactions that had not got a value except for "0.00000001" (as displayed on the released version), and "0.00000000" when opened in PR1001.
Screen Shot 2022-04-29 at 9 37 57 am
The beachball of waiting is invisible in the screenshot, but it is still there.

**Comment by us77ipis** [comment]
That sounds like a locking issue. I think I forgot to lock also `cs_main`. @seanPhill Please try again with the changes I just pushed.

**Comment by us77ipis** [comment]
> There was probably at least thirty or forty CT (from incoming zerocoin spends) incoming transactions that had not got a value except for "0.00000001" (as displayed on the released version), and "0.00000000" when opened in PR1001.

That's the expected behavior for transactions that had already arrived before. For the "Hidden" text to be displayed the transaction has to have income through the wallet that has the changes of this PR. However, once you unlock the wallet (and it doesn't hang up) also the old "0.00000000" values should be replaced by the correct ones.

File: src/qt/transactiontablemodel.cpp [hunk 1]
```diff
@@ -120,6 +120,20 @@ class TransactionTablePriv
 
         switch(status)
         {
+        case CT_UPDATED_FULL:
+        case CT_DELETED:
+            if(!inModel)
+            {
+                qWarning() << "TransactionTablePriv::updateWallet: Warning: Got CT_DELETED, but transaction is not in model";
```
Comment (Zannick) [inline src/qt/transactiontablemodel.cpp:127]: This warning should say CT_UPDATED_FULL instead if that's the status.

File: src/qt/transactiontablemodel.cpp [hunk 2]
```diff
@@ -120,6 +120,20 @@ class TransactionTablePriv
...
+                break;
+            }
+            // Removed -- remove entire transaction from table
+            parent->beginRemoveRows(QModelIndex(), lowerIndex, upperIndex-1);
+            cachedWallet.erase(lower, upper);
+            parent->endRemoveRows();
+            if (status == CT_DELETED)
+                break;
+            inModel = false;
```
Comment (Zannick) [inline src/qt/transactiontablemodel.cpp:136]: Please do not implicitly fall through. I recommend inverting the if statement if you meant to break here after inModel = false.

File: src/veil/ringct/anonwallet.cpp [hunk 3]
```diff
@@ -4025,13 +4025,18 @@ bool AnonWallet::UnlockWallet(const CExtKey& keyMasterIn)
...
     AnonWalletDB wdb(*walletDatabase);
     if (!wdb.ReadNamedExtKeyId("stealthchange", idChangeAccount)) {
         //If the change account is not created yet, then create it
         if (!CreateStealthChangeAccount(&wdb))
             return error("%s: failed to create stealth change account ", __func__);
     }
+    }
+
+    LOCK2(cs_main, pwalletParent->cs_wallet);
+    RescanWallet();
```
Comment (Zannick) [inline src/veil/ringct/anonwallet.cpp:4039]: This may be a good opportunity to mark RescanWallet with `EXCLUSIVE_LOCKS_REQUIRED` annotations if it always needs these locks, that way clang can catch issues like that in the future.

**Review by Zannick — CHANGES_REQUESTED** [review]

File: src/qt/transactiontablemodel.cpp (hunk 2 above)
Comment (us77ipis) [reply src/qt/transactiontablemodel.cpp:136]: Fall through is intentional here to prevent code duplication, since `CT_UPDATED_FULL` is equivalent to first `CT_DELETED` and then `CT_NEW`.

Comment (Zannick) [reply src/qt/transactiontablemodel.cpp:136]: Ok, then please add a comment explaining the fallthrough is intentional.

Comment (us77ipis) [reply src/qt/transactiontablemodel.cpp:136]: Okay, I'll do that

**Comment by seanPhill** [comment]
Tested a second time with the changes at the point in time of my thumbs up above.
Fully worked as expected. This wallet took just a few minutes, but a smaller wallet would have been quicker.
Screen Shot 2022-04-29 at 4 01 54 pm
Screen Shot 2022-04-29 at 4 03 04 pm
Screen Shot 2022-04-29 at 4 04 07 pm
Screen Shot 2022-04-29 at 4 04 29 pm
Screen Shot 2022-04-29 at 4 04 55 pm
Screen Shot 2022-04-29 at 4 05 35 pm

**Comment by us77ipis** [comment]
This PR is now ready for extensive testing and review.

**Comment by us77ipis** [comment]
I don't know how the translation stuff currently works. Since I added the new strings "Hidden" and "Unlock wallet to see hidden amount", should some translations be added? If yes, how exactly is that handled?

**Comment by seanPhill** [comment]
I just had an issue with this function tonight. [Don't know if this is related to the requested changes.] 

While it has normally worked fine for me, my testnet wallet had been locked (and / or closed) and receiving a lot of transactions for about twenty hours, and maybe I unlocked it a bit soon after starting it up, but when I did, the transactions this time did not correct themselves. I was still getting the mouseover message about needing to unlock to see the correct amounts. I waited a few minutes, and tried locking the wallet again and unlocking it again, and it still did not correct the transactions list. ... I then manually did `rescanringctwallet`, and it promptly fixed all the amounts.

This is a wallet with over 55,000 transaction rows in the course of twenty days from fresh seed. The issue was with the 62 received CT amounts over the course of 20 hours, while the wallet was either locked or turned off.

**Comment by us77ipis** [comment]
> [Don't know if this is related to the requested changes.]

I already pushed the requested changes (and marked them as solved), don't know why it still shows "Changes requested".

> I then manually did rescanringctwallet, and it promptly fixed all the amounts.

If full `rescanringctwallet` worked, then that is an issue with the optimization, thus for whatever reason those transactions didn't get tracked as locked transactions.

**Comment by seanPhill** [comment]
@Zannick can you confirm that your requested changes have been made? ... -> code review. Everything should be ready.

**Review by Zannick — APPROVED** [review]
utACK 6333d875984d0cecaceefa6d2f7a830755274a44

Confirmed that the changes I requested were addressed. ("Changes requested" always shows if someone's last review was "Request changes", sorry it took so long to update the review.)

**Comment by WetOne** [comment]
utACK 6333d875984d0cecaceefa6d2f7a830755274a44

**Review by WetOne — APPROVED** [review]

**Comment by seanPhill** [comment]
This PR solves the issue that caused an exchange in early 2019 to reverse their decision to allow stealth withdrawals.
I hope that this PR can be included in the next release, which will enable exchanges to enable stealth withdrawals. @codeofalltrades
