### PR TITLE
[Qt] Fixes cut off tool tip text across the application

### LINKED ISSUE #54: When hovering over "Start Veil Core on system login", the pop-up tooltip is not fully visible.
https://i.imgur.com/puTLH0Y.png

30.5. When hovering over "Start Veil Core on system login", the pop-up tooltip is not fully visible. It is cut off vertically.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

### LINKED ISSUE #63: Cut off tooltip
Sometimes the tooltip cuts off and works again after another tooltip rendered fully.
Screenshot below:

@veildev

### PR DESCRIPTION
**Pull request by codeofalltrades**
Set the style sheet at the application level. This is a workaround provided by the Qt developers to stop cut off text in tooltips.
QT-BUG: https://bugreports.qt.io/browse/QTBUG-64550
QT-BUG: https://bugreports.qt.io/browse/QTBUG-41313

All tooltips will have a light blue background.

fixes #63 
fixes #54

### CODE REVIEW

**Comment by ncrypter90** [comment]
QA in progress..

**Comment by ncrypter90** [comment]
observation:
Text or options in each tab are misaligned .
tab 1
image
tab 2
image

**Comment by ncrypter90** [comment]
Bug:

The build works fine on windows and linux but in Mac text back ground is transparent when user hover the mouse on the option for the first time but when pointed moved to other option and come back then it shows black background.

image

File: src/qt/optionsdialog.cpp [hunk 1]
```diff
@@ -86,15 +86,38 @@ OptionsDialog::OptionsDialog(QWidget *parent, bool enableWallet) :
     if (!enableWallet) {
         ui->tabWidget->removeTab(ui->tabWidget->indexOf(ui->tabWallet));
     }
+	   
+	/*  Set the tooltip style here to override the OS style.*/
+    QString tooltipStyle = QString("QToolTip {color: #ffffff; background-color: #6f9bf5; font-size:11pt; border: none; border-radius:20px; padding:6px; margin:0px; min-height: 35px; qproperty-alignment: 'AlignVCenter | AlignCenter';}");
```
Comment (presstab) [inline src/qt/optionsdialog.cpp]: Is there a reason not to add the tooltip styling to `main.css` ? Veil has too much mixing and matching of stylesheets (.ui, in the .cpp, and in main.css), it seems much more preferable to edit the main stylesheet than to do it this way. Is this specifically needed to overcome the issue or would it still work if this styling were move to main.css?

Comment (codeofalltrades) [reply src/qt/optionsdialog.cpp]: @presstab Unfortunately the bugs in the Qt version we are using require this workaround to render the tooltips correctly. QT-QTBUG-64550 can be fixed by upgrading Qt versions. Bug QTBUG-41313 the missing background when set via CSS problem remains unresolved. 

Too make this not as bad, is there is way to make the tooltip style a global QString constant that can be reuse across the codebase?

QT-BUG: https://bugreports.qt.io/browse/QTBUG-64550
QT-BUG: https://bugreports.qt.io/browse/QTBUG-41313

Comment (paddingtonsoftware) [reply src/qt/optionsdialog.cpp]: Wow that is very agitating!

Comment (presstab) [reply src/qt/optionsdialog.cpp]: Very agitating. Hate when its a QT bug.

**Comment by presstab** [comment]
@codeofalltrades Will you squash down to one commit?

**Comment by ncrypter90** [comment]
QA Passed: 

Missing check boxes will be fixed in #546, that will be validated after the PR request.

File: src/qt/optionsdialog.cpp (hunk 1 above)
Comment (codeofalltrades) [reply src/qt/optionsdialog.cpp]: Agreed! I tried every fix I could locate and the only one that worked was this. I asked in the discord dev #gui channel about upgrading the Qt version. Fuzzbawls recommended against the upgrade for a host of reasons.

**Comment by codeofalltrades** [comment]
> 
> 
> @codeofalltrades Will you squash down to one commit?

@presstab squashed... It was my first time doing that hopefully I did it correctly.
